# cargo-features = ["codegen-backend"]
[package]
name = "tg"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.11", features = ["derive"] }
directories = "5.0.1"
yakv = { path = "./yakv" }
bitcode = "0.6.3"

[profile.dev]
debug = 0
# codegen-backend = "cranelift"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
