cargo-features = ["codegen-backend"]
[package]
name = "tg"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.11", features = ["derive"] }
directories = "5.0.1"
anyhow = { version = "1.0.86" }
libc = "0.2.155"
ctrlc = { version = "3.4.4", features = ["termination"] }
rusqlite = { version = "0.32.1", features = ["bundled"] }
fuse3 = { version = "0.7.2", features = ["tokio-runtime", "unprivileged"] }
futures-util = "0.3.30"
tokio = { version = "1.39.2", features = ["macros", "rt", "rt-multi-thread", "signal", "time"] }

[dev-dependencies]
fake = "2.9.2"
rand = "0.8.5"

[profile.dev]
debug = 0
codegen-backend = "cranelift"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
