cargo-features = ["codegen-backend"]
[package]
name = "tg"
version = "0.1.0"
edition = "2021"

[dependencies]
# bonsaidb = { version = "0.5.0", features = ["local"] }
clap = { version = "4.5.11", features = ["derive"] }
directories = "5.0.1"
fake = "2.9.2"
# pickledb = { version = "0.5.1", default-features = false, features = ["bincode"] }
rand = "0.8.5"
serde = "1.0.204"
yakv = "0.2.7"

[profile.dev]
debug = 0
codegen-backend = "cranelift"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
